// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// calculateDSSPAccessibility
Rcpp::NumericVector calculateDSSPAccessibility(Rcpp::DataFrame atoms, Rcpp::DataFrame residues);
RcppExport SEXP _evopatchr_calculateDSSPAccessibility(SEXP atomsSEXP, SEXP residuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type atoms(atomsSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type residues(residuesSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateDSSPAccessibility(atoms, residues));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_evopatchr_calculateDSSPAccessibility", (DL_FUNC) &_evopatchr_calculateDSSPAccessibility, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_evopatchr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
